### Configuration file for the SFG GitHub page (hosted by Netlify).
### Built using the Hugo Universal Theme by Bootstrapious, adapted for Hugo by DevCows, and modified by kmillage
### Last updated on March 26, 2018

### General settings -------------------------------------
baseurl = "/" # Later will try to link this to the sfg-ucsb.github.io page
title = "Sustainable Fisheries Group"
theme = "modified-hugo-universal-theme"
themesDir = "./themes"
languageCode = "en-us" 
defaultContentLanguage = "en" # Site language. Available translations in the theme's `/i18n` directory.
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking code
paginate = 10 # Define the number of posts per page

### Menu settings -----------------------------------------
[menu]

# Main menu
[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "Open Science"
    identifier = "publications"
    url  = "/publications/"
    weight = 3
    
[[menu.main]]
    name = "About Us"
    identifier = "about"
    url  = "/about/"
    weight = 4

# Footer contact icons (ignore that it says topbar... changed this from original template and changing the name will probably break everything)
[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/SFG-UCSB"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "https://twitter.com/sfgucsb?lang=en"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "Instagram"
    url = "https://www.instagram.com/sfg_ucsb/"
    pre = "<i class='fa fa-2x fa-instagram'></i>"

### Parameters -----------------------------------------
[params]

### General parameters ---------------------------------
    date_format = "January 2, 2006" # Format dates with Go's time formatting

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Footer
    copyright = "Copyright (c) 2018, Sustainable Fisheries Group; all rights reserved."

    footer_text = """<p class="hidden-sm hidden-xs">Visit our main website at <a href="http://sfg.msi.ucsb.edu/">http://sfg.msi.ucsb.edu/</a> or you can find us on Github, Twitter, and Instagram! </p>
      <p class="hidden-md hidden-lg"></p>"""
      
### Contact page ###      
# Since this template is static, the contact form uses www.formspree.io as a proxy. 
#The form makes a POST request to their servers to send the actual email. 
#Visitors can send up to a 1000 emails each month for free.
  
# What you need to do for the setup?
# - set your email address under 'email' below
# - upload the generated site to your server
# - send a dummy email yourself to confirm your account
# - click the confirm link in the email from www.formspree.io

# Enable the contact form by entering your Formspree.io email
    email = "your@email.com"

    logo = ""
    address = ""
      
    viewMorePostLink = "/blog/"
    author = ""
    defaultKeywords = []
    defaultDescription = ""

    uglyurls = true
    
#[Permalinks]
    #blog = "/blog/:year/:month/:day/:filename/"
    #about = "/about/:filename/"

### Widget things -----------------------------------

# Carousel - Main header box on first page
# All carousel items are defined in their own files stored in '/data/carousel/'
[params.carousel]
    enable = true    

# Recent Posts - Box with set number of recent posts
# All posts are defined in their own files stored in '/content/blog/'
[params.recent_posts]
    enable = true
    title = "Recent posts from our blog"
    subtitle = "We like to write about code, random interests, etc..."
    
# See More - Send people to the main SFG web page
[params.see_more]
    enable = true
    title = "Do you want to learn more about us?"
    subtitle = "Find more information on our team, projects, and places we work on our main website"
    link_url = "http://sfg.msi.ucsb.edu/"
    link_text = "Visit our main site"
    
# Features - Box with different icons and short descriptions
# All features are defined in their own files stored in '/data/features/'
[params.features]
    enable = false
    
# Testimonials - Box with quotes, names, and pictures of various people... Might put staff here
# All testimonials are defined in their own files stored in '/data/testimonials/'
[params.testimonials]
    enable = false
    title = ""
    subtitle = ""

# Clients - Box with logos that link to external sites. Probably not using this section
# All clients are defined in their own files stored in '/data/clients/'
[params.clients]
    enable = false
    title = ""
    subtitle = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true
    authors = true




