---
title: SFG Looks to the Sky to Understand the Sea
date: "2017-07-12"
authors: ["Tyler Clavelle"]
tags: ["SFG", "Google"]
categories: ["News"]
banner: "img/blog/under-the-sea.jpg"
cover: "img/blog/under-the-sea-cover.jpg"
output: 
  blogdown::html_page:
    toc: FALSE
---

In June, SFG team members Tyler Clavelle, Grant McDermott, and Juan Mayorga traveled to Palo Alto, California to participate in the 2017 User Summit for Google’s Earth Engine (GEE), a planetary-scale platform for earth science data and analysis. GEE is transforming geospatial research by enabling scientists to ask and answer questions at scales that have never before been possible. Since it’s inception in 2010, researchers have used GEE for hundreds of groundbreaking studies and applications, such as mapping global forest cover, surface water, and malaria risk, in high-resolution. We had an incredible experience at the 2017 GEE User Summit and left with an expanded toolkit that we'll leverage as we integrate more and more big data approaches into our research.

SFG is currently using GEE to support a portfolio of several exciting projects. First, in collaboration with our Global Fishing Watch (GFW) partners, SFG is creating comprehensive maps of global fishing effort that will be publicly available and can be used by researchers via GEE later this summer. GFW uses satellite Automated Information Systems (AIS) data to create a massive database of fishing effort around the world and monitor fishing activity in near-real time. Our team is using these data to tackle a diverse set of ocean challenges, including illegal fishing, overfishing, and human rights abuses aboard fishing vessels. Together with GFW data, Earth Engine is emerging as one of the most powerful platforms for SFG and other researchers to study global fisheries and inform conservation measures and management interventions.

Our team is also using GEE to answer big questions about sustainable marine aquaculture--also known as mariculture--on a global scale. Aquaculture now produces more seafood for human consumption than wild fisheries, but the information we have about where production occurs is extremely limited. To fill this information gap, SFG’s Tyler Clavelle is using GEE and machine learning to identify mariculture farms in satellite images and estimate the sector’s global footprint. This information is fundamental to understanding mariculture’s productivity, sustainability, and the ways it interacts with wild fisheries and the environment as the sector continues to expand.

